---
# Install default packages

- name: Install pip
  ansible.builtin.apt:
    name: pip
    state: present
    update_cache: true

- name: Install cpufrequtils
  ansible.builtin.apt:
    name: cpufrequtils
    state: present
    update_cache: true

- name: Install ufw
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: true
  notify: Start ufw