---
# tasks file for common

- name: "Create facts directory"
  ansible.builtin.file:
    dest: "{{ ansible_path }}/facts.d"
    state: directory
    owner: root
    group: root
    mode: "0644"

- name: Install depends
  ansible.builtin.include_tasks: install_depends.yml

- name: Install packages
  ansible.builtin.include_tasks: install_packages.yml

- name: Configurate iptables
  ansible.builtin.include_tasks: configurate_iptables.yml

- name: Configurate ssh
  ansible.builtin.include_tasks: configurate_ssh.yml

- name: Configurate turboboost
  ansible.builtin.include_tasks: configurate_turboboost.yml